apiVersion: v1
kind: Pod
metadata:
  name: app-mongo-si
  labels:
    app: app-mongo-si
spec:
  containers:
  - name: app-mongo-container
    image: mazins/ndb-operator-mongodb:latest
    env:
    - name: DBHOST                              
      value: <db-name>-svc                   # CHANGE
    - name: DBPORT
      value: "80"                            # CHANGE
    - name: DATABASE
      value: database_one                    # CHANGE 
    - name: USERNAME
      value: admin                           # CHANGE. Use 'admin'
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-instance-secret-name      # CHANGE
          key: password 
    ports:
    - containerPort: 3000
  initContainers:
    - name: init-db
      image: busybox:1.28
      command: ['sh', '-c', "until nslookup $(DB_HOST).$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for $(DB_HOST); sleep 2; done"]
      env:
      - name: DB_HOST 
        value: <db-name>-svc                 # CHANGE
