apiVersion: v1
kind: Pod
metadata:
  name: app-mssql-si
  labels:
    app: app-mssql-si
spec:
  containers:
  - name: app-mssql-container
    image: mazins/ndb-operator-mssql:latest
    env:
    - name: DBHOST 
      value: <db-name>-svc       
    - name: DBPORT
      value: "80"
    - name: DATABASE
      value: database_one         
    - name: USERNAME
      value: admin # use 'admin'        
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-instance-secret-name
          key: password 
    ports:
    - containerPort: 3000
  initContainers:
    - name: init-db
      image: busybox:1.28
      command: ['sh', '-c', "until nslookup $(DB_HOST).$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for $(DB_HOST); sleep 2; done"]
      env:
      - name: DB_HOST 
        value: <db-name>-svc     
