apiVersion: v1
kind: Pod
metadata:
  name: app-mysql-si
  labels:
    app: app-mysql-si
spec:
  containers:
  - name: app-mysql-container
    image: mazins/ndb-operator-mysql:latest
    env:
    - name: DBHOST 
      value: <db-name>-svc                 # CHANGE
    - name: DBPORT
      value: '3306'                        # CHANGE
    - name: DATABASE
      value: database_one                  # CHANGE       
    - name: USERNAME
      value: root                          # CHANGE. Use 'root'
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-instance-secret-name    # CHANGE      
          key: password 
    ports:
    - containerPort: 3000
  initContainers:
    - name: init-db
      image: busybox:1.28
      command: ['sh', '-c', "until nslookup $(DB_HOST).$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for $(DB_HOST); sleep 2; done"]
      env:
      - name: DB_HOST 
        value: <db-name>-svc               # CHANGE      
